### ISSUE TITLE
This is not an issue :)!

### ISSUE THREAD

**Issue by kberov** [BlameTroi/fpc-vim#1]
Thanks for starting this endeavor. I come form other languages like Perl,JS,Go... and I use VIM for the last 15+ years. I am just another vim user. Did not try to learn VimScript ever.

Recently I decided to learn [Pascal](https://wiki.freepascal.org/). I felt strange when I found out that I cannot use vim for Pascal. I will try the plugin and will try to report some findings at least if not else.
Thank you!

**Comment by BlameTroi** [comment]
Hi. I've moved to Emacs since Braam passed and it's clear that the
vim/neovim split is going to get worse. I had a little better luck there.
All the recent Pascal style tooling seems geared toward forms based
programming on Windows (Delphi, Lazarus), which is a pity.

After more recent work in Fortran and C with LSPs, I've personally decided
that the best I can hope to get in either Emacs or Vim is reasonable
indenting as I edit. For proper formatting a "format on save" option as is
the norm with golang seems best. I thought about make ptop (Pascal
formatter available in source) work in a manner similar to astyle or
fprettify (stream input and output instead of files) but since I'm using
Fortran for the things I was doing in Pascal, I never started.

Best regards.

**Comment by kberov** [comment]
Ok. Oh, pity.
